---
output:
  html_document:
    toc: true
    number_sections: false
    toc_depth: 3
author: "Carl Beuchel"
date: "`r format(Sys.time(), '%d %B, %Y')`"
editor_options: 
  chunk_output_type: console
---

```{r knitr, cache = F, results = "markup", echo = T, warning = T}
# start with a clean workspace
rm(list=ls())
gc()

# Set the global knitr options
knitr::opts_chunk$set(cache = F, results = "hide", echo = T ,include = T)

# what should the output file be called?
filename = "STEP 2: Zero-inflated data exploration"
```

# `r filename`
***
This script is a small data simulation to help figure out an appropriate data transformation withouth loosing too much statistical power in the subsequent regression analyses.

```{r initiate, cache = F, results = "hide", echo = F}
# choose correct working directory
r_on_server <- T
if (r_on_server == T) {
  basicpath <- "/net/ifs1/san_projekte/projekte/"
} else {
  basicpath <- "/mnt/ifs1_projekte/"
}
setwd(basicpath)

# set working directory
pathwd <-
  paste0(
    basicpath,
    "genstat/02_projekte/1703_ge_metab_a1_b3_sorbs/171124_ZeroInflatedDataSim"
  )
setwd(pathwd)

# get additional functions from Holger Kirstens newest RProfile file
newest_rprofile <-
  function(designation = paste0(basicpath, "genstat/07_programme/rtools/RProfile_hk/")) {
    files <- list.files(designation)
    RProfiles <- files[grep("Rprofile_hk_", files)]
    newest_RProfile <- tail(sort(RProfiles), n = 1)
    suppressPackageStartupMessages(source(paste0(designation, newest_RProfile)))
  }
newest_rprofile()

# start time measurement, define alternative package directory, define start codes for external start of the script
if (r_on_server == T) {
  initializeSkript(myfilename = filename, computer = "forostar") # enter which server you are on
} else
  initializeSkript(myfilename = filename, computer = "local")

# Packages
for (i in c(
  "knitr",
  "data.table",
  "MASS",
  "ggplot2",
  "scales"
)) {
  suppressPackageStartupMessages(library(i, character.only = TRUE))
}
```

## Data simulation and setup

```{r load}
# load the simuation results
all.scenarios <- fread("/mnt/ifs1_projekte/genstat/02_projekte/1703_ge_metab_a1_b3_sorbs/171124_ZeroInflatedDataSim/results/171127_SimulationResults.csv")

# add fdr
all.scenarios[, linmod.fdr := p.adjust(p = linmod.pval, method = "BH")]
all.scenarios[, dicho.fdr := p.adjust(p = dicho.pval, method = "BH")]
all.scenarios[, logit.fdr := p.adjust(p = logit.pval, method = "BH")]

```

```{r add.func}
# Multiple plot function
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```

## Plot pvalues against each other

```{r explore}
# dicho pvalues plotted against linmod pvalues for different effect sizes
pdf("/mnt/ifs1_projekte/genstat/02_projekte/1703_ge_metab_a1_b3_sorbs/171124_ZeroInflatedDataSim/plots/171128_dicho&LogitVsLinmodPvalsPerEffekt.pdf", width = 21)
lapply(unique(all.scenarios$effekt), function(x){
  
  p1 <- ggplot(all.scenarios[proz0 == 20 & effekt == x, ], aes(linmod.pval, dicho.pval, colour = logit.pval)) +
    geom_point() +
    facet_grid(categart ~ categnum, scales = "free") +
    scale_x_continuous(breaks = pretty_breaks(4)) +
    scale_y_continuous(breaks = pretty_breaks(10)) +
    theme_minimal() + 
    ggtitle(label = paste0("dicho ~ linmod pvalues for effect size of ", x)) +
    scale_color_distiller(palette="Spectral")
  
  p2 <- ggplot(all.scenarios[proz0 == 20 & effekt == x, ], aes(linmod.pval, logit.pval, color = dicho.pval)) +
    geom_point() +
    facet_grid(categart ~ categnum, scales = "free") +
    scale_x_continuous(breaks = pretty_breaks(4)) +
    scale_y_continuous(breaks = pretty_breaks(10)) +
    theme_minimal() +
    ggtitle(label = paste0("logit ~ linmod pvalues for effect size of ", x)) +
    scale_color_distiller(palette="Spectral")
  
  multiplot(p1, p2, cols = 2)
})
dev.off()

# dicho.pval ~ logit.pval
pdf("/mnt/ifs1_projekte/genstat/02_projekte/1703_ge_metab_a1_b3_sorbs/171124_ZeroInflatedDataSim/plots/171128_logitVsDichoPvalsPerEffect&0infl.pdf", width = 21)
lapply(unique(all.scenarios$proz0), function(y){
  lapply(unique(all.scenarios$effekt), function(x){
  
ggplot(all.scenarios[proz0 == y & effekt == x, ], aes(logit.pval, dicho.pval, colour = linmod.pval)) +
    geom_point() +
    facet_grid(categart ~ categnum, scales = "free") +
    scale_x_continuous(breaks = pretty_breaks(4)) +
    scale_y_continuous(breaks = pretty_breaks(5)) +
    theme_minimal() + 
    ggtitle(label = "dicho ~ logit pvalues", subtitle = paste0("Effect-size= ", x, " and zero-inflation by ", y, "%")) +
    scale_color_distiller(palette="Spectral")
  })
})
dev.off()

# filter by pvalue, e.g. only those with high dicho pval etc
# dicho.pval ~ logit.pval
pdf("/mnt/ifs1_projekte/genstat/02_projekte/1703_ge_metab_a1_b3_sorbs/171124_ZeroInflatedDataSim/plots/171128_logitVsDichoPvalsPerEffect&0infl&FDRFiltered", width = 21)
lapply(unique(all.scenarios$proz0), function(y){
  lapply(unique(all.scenarios$effekt), function(x){
  
ggplot(all.scenarios[proz0 == y & effekt == x & linmod.fdr <= 0.05, ], aes(logit.pval, dicho.pval, colour = linmod.pval)) +
    geom_point() +
    facet_grid(categart ~ categnum, scales = "free") +
    scale_x_continuous(breaks = pretty_breaks(4)) +
    scale_y_continuous(breaks = pretty_breaks(5)) +
    theme_minimal() + 
    ggtitle(label = "dicho ~ logit pvalues", subtitle = paste0("Effect-size= ", x, " and zero-inflation by ", y, "%")) +
    scale_color_distiller(palette="Spectral")
  })
})
dev.off()

# number of categories as deciding factor
all.scenarios[linmod.fdr <= 0.05, sum(logit.fdr <= 0.05), by = .(categart,categnum)]
all.scenarios[linmod.fdr <= 0.05, sum(dicho.fdr <= 0.05), by = .(categart,categnum)]
```

```{r boxplots}
# based on fdr-corrected linmod pvals, show boxplot of pvalue distribution of all three methods
test <- melt(data = all.scenarios[linmod.fdr <= 0.05, ], id.vars = c("effekt", "proz0", "categart", "categnum"), measure.vars = c("dicho.pval", "linmod.pval", "logit.pval"))

# for all linmod.fdr <= 0.05 plot the pvalue distribution for each effekt and zero-inflation percentage
pdf("/mnt/ifs1_projekte/genstat/02_projekte/1703_ge_metab_a1_b3_sorbs/171124_ZeroInflatedDataSim/plots/171128_logitVsDichoPvalsBoxPlotByLinmodFDR005.pdf")

# outer loop for proz0
lapply(unique(all.scenarios$proz0), function(y){
  
  # inner loop for effect size
  lapply(unique(all.scenarios$effekt), function(x){
    
    ggplot(test[proz0 == y & effekt == x], aes(x = as.factor(categnum), y = value, fill = variable)) + 
      geom_boxplot() + coord_flip() + 
      facet_wrap( ~ categart, scales = "free_x") + 
      scale_fill_brewer(palette="Spectral") +
      ggtitle(label = "dicho, logit & linmod pvalues for linmod.pval FDR <= 0.05", subtitle = paste0("Effect-size = ", x, " and zero-inflation by ", y, "%")) +
      theme_minimal()
  })
})

dev.off()


# show boxplot of pvalue distribution of all three methods for all pvalues
test.2 <- melt(data = all.scenarios, id.vars = c("effekt", "proz0", "categart", "categnum"), measure.vars = c("dicho.pval", "linmod.pval", "logit.pval"))

# for all linmod.fdr <= 0.05 plot the pvalue distribution 
pdf("/mnt/ifs1_projekte/genstat/02_projekte/1703_ge_metab_a1_b3_sorbs/171124_ZeroInflatedDataSim/plots/171128_logitVsDichoBoxRawPvals.pdf")

# outer loop for proz0
lapply(unique(all.scenarios$proz0), function(y){
  
  # inner loop for effect size
  lapply(unique(all.scenarios$effekt), function(x){
    
    ggplot(test.2[proz0 == y & effekt == x], aes(x = as.factor(categnum), y = value, fill = variable)) + 
      geom_boxplot() + coord_flip() + 
      facet_wrap( ~ categart, scales = "free_x") + 
      scale_fill_brewer(palette="Spectral") +
      ggtitle(label = "dicho, logit & linmod pvalues", subtitle = paste0("Effect-size = ", x, " and zero-inflation by ", y, "%")) +
      theme_minimal()
  })
})

dev.off()

# boxplot of FDR pvals for all linmod FDR <= 0.05 
test.3 <- melt(data = all.scenarios[linmod.fdr <= 0.05, ], id.vars = c("effekt", "proz0", "categart", "categnum"), measure.vars = c("dicho.fdr", "linmod.fdr", "logit.fdr"))

# for all linmod.fdr <= 0.05 plot the pvalue distribution for each effekt and zero-inflation percentage
pdf("/mnt/ifs1_projekte/genstat/02_projekte/1703_ge_metab_a1_b3_sorbs/171124_ZeroInflatedDataSim/plots/171128_logitVsDichoFDRPvalsBoxPlotByLinmodFDR005.pdf")

# outer loop for proz0
lapply(unique(all.scenarios$proz0), function(y){
  
  # inner loop for effect size
  lapply(unique(all.scenarios$effekt), function(x){
    
    ggplot(test.3[proz0 == y & effekt == x], aes(x = as.factor(categnum), y = value, fill = variable)) + 
      geom_boxplot() + coord_flip() + 
      facet_wrap( ~ categart, scales = "free_x") + 
      scale_fill_brewer(palette="Spectral") +
      ggtitle(label = "dicho, logit & linmod FDR pvalues for linmod.pval FDR <= 0.05", subtitle = paste0("Effect-size = ", x, " and zero-inflation by ", y, "%")) +
      theme_minimal()
  })
})

dev.off()
```

```{r zoom.in}
# logit seems to outperform dicho glm
# look more closely at logit vs lm
# betas correlate well
ggplot(all.scenarios[effekt == 0.01 & proz0 == 20 & categart == "quantile" & categnum == 2, ], aes(x = linmod.beta, y = logit.beta)) +
  geom_point()

# pvalues not so much
ggplot(all.scenarios[effekt == 0.01 & proz0 == 20 & categart == "quantile" & categnum == 2, ], aes(x = linmod.pval, y = logit.pval)) +
  geom_point()

# check out other statistics 
test.4 <- melt(data = all.scenarios[linmod.fdr <= 0.05, ], id.vars = c("effekt", "proz0", "categart", "categnum"), measure.vars = c("linmod.fdr", "logit.fdr", "logit.pval", "linmod.pval", "linmod.r2", "linmod.beta", "logit.beta"))

pdf("/mnt/ifs1_projekte/genstat/02_projekte/1703_ge_metab_a1_b3_sorbs/171124_ZeroInflatedDataSim/plots/171130_logitPvalsByEffectPerCategory.pdf", height = 14)
# look at logit pvals 
ggplot(test.4[proz0 == 20 & effekt %in% c(0.01, 0.02, 0.05) & variable == "logit.pval", ], aes(y= value, x = as.factor(categnum), fill = as.factor(effekt))) +
  geom_boxplot() +
  facet_grid( ~ as.factor(categart)) + 
  coord_flip(ylim = c(0,0.1)) +
  scale_fill_brewer(palette="Spectral") +
  theme_minimal()
dev.off()
```

```{r save}
# write.table(x = all.scenarios,
#             file = paste0(pathwd, "/results/",
#                           format(Sys.time(), '%y%m%d'),
#                           "_SimulationResults.csv"),
#             sep = "\t", row.names = F)
```

```{r SessionInfo, echo=F, results='markup'}
sessionInfo()
```            