---
output:
html_document:
toc: true
number_sections: false
toc_depth: 3
author: "Carl Beuchel"
date: "`r format(Sys.time(), '%d %B, %Y')`"
editor_options: 
  chunk_output_type: console
---

***
This script is a small data simulation to help figure out an appropriate data transformation withouth loosing too much statistical power in the subsequent regression analyses.

```{r initiate, cache = F, results = "hide", echo = F}
# choose correct working directory
r_on_server <- T

# number of cores used in parallel processing
if (r_on_server == T) {
  .libPaths("/net/ifs1/san_projekte/projekte/genstat/07_programme/rpackages/amanMRO/")
  number.of.cores <- 15
  bp <- "/net/ifs1/san_projekte/projekte"
} else {
  number.of.cores <- parallel::detectCores()/2
  bp <- "/net/ifs1/san_projekte/projekte"
  # bp <- "/mnt/mount1/"
}

# Packages
for (i in c(
  "knitr",
  "data.table",
  "broom",
  "ordinal",
  "sva",
  "MASS",
  "parallel",
  "CarlHelpR",
  "toolboxH",
  "here",
  "bestNormalize"
)) {
  suppressPackageStartupMessages(library(i, character.only = TRUE))
}

# set up for parallelisation

# source small function
source(here("RCode/batch_anova.R"))
```

```{r knitr, cache = F, results = "markup", echo = T, warning = T}
gc()

# Set the global knitr options
knitr::opts_chunk$set(cache = F, results = "hide", echo = T ,include = T)

# what should the output file be called?
filename = "STEP 1: Zero-inflated data simulation"
```

# `r filename`

## Data simulation and setup

```{r param.setup}
# code by HKirsten (holgerman)
# set parameters for simulation, e.g. effect size, n...
set.seed(0815)

# magnitude of simulated effect  
effekte.input = c(0, 0.01, 0.02, sqrt(0.025), 0.05, 0.1, 0.2, 0.3)
# effekte.input = sqrt(c(0, 0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04, 0.045, 0.05))

# size of simulated data set
n.input = c(3000)

# magnitude of zero-inflation in %
proz0.input = c(0, 20, 50, 80)

# how often should each step be repeated?
realisierungen.input = 1000

# type of categories
categart.input = c("quantile", "bereiche")
# categart.input = c("quantile") #, "bereiche")

# number of categories
# categnum.input = c(10)
categnum.input = c(5, 10, 20, 30, 40, 50)

# add a batch to test the effect of ComBat on badly distributed data
# batch.effekt.input <- c(1)
batch.effekt.input <- c(0, 1)

batch.nr.input <- 10
```

## Create scenarios

```{r create.scenarios}
# create dt with all scenario combinations
szenarien <- data.table(expand.grid(effekte = effekte.input,
                                    n = n.input,
                                    proz0 = proz0.input,
                                    categart = categart.input,
                                    categnum = categnum.input,
                                    batch = batch.effekt.input,
                                    realization = 1:realisierungen.input))
szenarien[,num := 1:.N]

# combat ID bauen
# szenarien (alle effekte, proz0 und 4 realisierungen pro combat run)
setorder(szenarien, effekte, n, proz0, categart, categnum, batch, realization)
# szenarien[, realisation.groups := sort(rep(1:(realisierungen.input /  2), 4))]
szenarien[, realisation.groups := sort(rep(1:(realisierungen.input /  2), 4))]
szenarien[, combat.run := paste(n, categart, categnum, batch, realisation.groups)]
szenarien[, combat.run := as.numeric(factor(combat.run))]
szenarien[, .N, combat.run][, .N, N]
```

## Create data and run lm

```{r test.data, warning=T}
options(nwarnings = 50000)
parallelisiere(proc = number.of.cores)
# apply over each szenario
#=================================================================================#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
all.combat.runs.raw <- mclapply(sort(unique(szenarien$combat.run)),  function(x) { # OUTER LOOP
  
  # create sub-scenario
  # x <- 251 # debug
  message(paste("\nStarting run:", x, "of", max(unique(szenarien$combat.run)), "#==============================================#\n"))
  my.combat.run <- szenarien[combat.run == x, ]
  my.combat.run[, sub.run := 1:.N]
  
  # subloop for each combat run
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  combat.data.raw <- lapply(my.combat.run$sub.run, function(i){ # INNER LOOP
    
    # i <- 85 # debug
    my.x <- my.combat.run[sub.run == i]
    
    # reassign the effects for readability
    my.effekt <- my.x$effekte
    my.n <- my.x$n
    my.proz0 <- my.x$proz0
    my.categart <- as.character(my.x$categart)
    my.categnum <- my.x$categnum
    my.num <- my.x$num
    my.batch.effekt <- my.x$batch
    my.real <-  my.x$realization
    
    # better draw data from multinominial normal distribution
    dm <- MASS::mvrnorm(n = my.n,
                        mu = c(5,5), # the mean of the distribution
                        Sigma = matrix(c(1, my.effekt, my.effekt, 1),
                                       nrow = 2, ncol = 2))
    df <- as.data.frame(dm)
    setDT(df)
    
    # set names
    names(df) <- c("x", "y")
    
    # get lognormal data for y
    df[, y := exp(y)]
    
    # create data for scenario
    # df1 <- data.table(x = rnorm(my.n, 3, 1)) # change for plotting of transformation effect from 3 to 0
    # df1[, y :=  (my.effekt * x) + ((1 - my.effekt) * rnorm(my.n, 3, 1))]
    
    # add batch effects do df
    df[, batch := rep_len(letters[1:batch.nr.input], length.out = my.n)]
    df[, batch.factor := as.numeric(factor(batch))]
    df[ , y := y + my.batch.effekt/batch.factor]
    
    #-----------------------------------------------------------------
    # create zero-inflated y-derived data
    #-----------------------------------------------------------------
    
    ### NEW  ###
    # do not do offset when my.proz0 == 0
    
    if(my.proz0 != 0){
    # way one:
    df[, y.0infl := y]
    df[y < quantile(y.0infl, probs = my.proz0/100), y.0infl := 0]
    min.found = df[y.0infl > 0, min(y.0infl)]
    df[y.0infl > 0, y.0infl := y.0infl - 0.99*min.found]
    } else {
      df[, y.0infl := y]
    }
    
    # check
    # df[,.N,y.0infl==0]
    # hist(df$y.0infl, breaks = 50)
    
    # keep only the first batch-name
    if(i == 1) {
      
      # build dt with dat
      combat.subgroup <- data.table(x = df$x,
                                    y = df$y,
                                    y.0infl = df$y.0infl,
                                    batch = df$batch)
      
      # name
      new.names <- c(paste0("x.", i), paste0("y.",i), paste0("y.0infl.", i), "batch")
      
      # only get the data for the other iterations
    } else if(i != 1) {
      
      # build dt with dat
      combat.subgroup <- data.table(x = df$x,
                                    y = df$y,
                                    y.0infl = df$y.0infl)
      
      # name
      new.names <- c(paste0("x.", i), paste0("y.",i), paste0("y.0infl.", i))
    }
    
    # set names
    setnames(combat.subgroup, new.names)
    
    # output
    return(combat.subgroup)
  }) # END INNER LOOP
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  
  # bind togeter
  invisible(combat.data <- do.call(cbind, combat.data.raw))
  
  #-----------------------------------------------------------------
  # Inverse-normal transformation of full and zero-inflated data
  #-----------------------------------------------------------------
  
  # what do I want to transform also only choose cols that have at least 20% zero inflation
  transform.full.cols <- names(combat.data)[grep("y.[0-9]+$", names(combat.data))] #[my.combat.run$proz0 != 0]
  transform.0infl.cols <- names(combat.data)[grep("y.0infl.[0-9]+$", names(combat.data))] #[my.combat.run$proz0 != 0]
  
  # all cols (full and zero-inflated)
  cols.to.transform <- c(transform.full.cols, transform.0infl.cols)
  
  # Loop -------------------------------
  transformed.cols <- combat.data[, lapply(.SD, function(x){
    
    # x <- combat.data$y.0infl_6  # debug
    one.transformed.col <- orderNorm(x)$x.t
    
    # return to "transformed.cols"-output
    return(one.transformed.col)
    
    # end of lapply-loop
  }), .SDcols = cols.to.transform]
  # End: Loop --------------------------
  
  # set transformed cols into combat.data
  names(transformed.cols) <- paste0(names(transformed.cols), ".transformed")
  
  # re-enter transformed data
  combat.data[ , names(transformed.cols) := transformed.cols]
  
  # END: INT of full and zero-infl data 
  # -----------------------------------
  
  #-----------------------------------------------------------------
  # Asinh-Transformation of full and zero-inflated data
  #-----------------------------------------------------------------
  
  # Loop -------------------------------
  transformed.cols <- combat.data[, lapply(.SD, function(x){
    
    # x <- combat.data$y.0infl.1  # debug
    one.transformed.col <- asinh(x)
    
    # return to "transformed.cols"-output
    return(one.transformed.col)
    
    # end of lapply-loop
  }), .SDcols = cols.to.transform]
  # End: Loop -------------------------
  
  # re-enter transformed data
  combat.data[ , (cols.to.transform) := transformed.cols]

  
  # END: Asinh of full and zero-infl data 
  # -----------------------------------
  
  #-----------------------------------------------------------------
  # do ComBat batch adjustment
  #-----------------------------------------------------------------
  
  # I need to do 4 batch adjustments
  # y
  # y.0infl
  # y.transformed
  # y.0infl.transformed
  
  # batch adjust the UNTRANSFORMED (y and y.0infl) and TRANSFORMED (y.*.transformed and y.0infl.*.transformed) data 
  # get cols 
  y.cols <- names(combat.data)[grep("^y.[0-9]+$", names(combat.data))]
  y.transformed.cols <- names(combat.data)[grep("^y.[0-9]+.transformed$", names(combat.data))]
  y.0infl.cols <- names(combat.data)[grep("y.0infl.[0-9]+$", names(combat.data))] # new name for consistency
  y.0infl.transformed.cols <- names(combat.data)[grep("y.0infl.[0-9]+.transformed$", names(combat.data))]
  
  #-----------------------------------------------------------------
  # Pre-ComBat ANOVA
  #-----------------------------------------------------------------
  
  # full.before.combat.aov <- batch_anova(data = combat.data,
  #                                       to.adjust = y.cols,
  #                                       batch = "batch")
  # 
  # full.after.transform.before.combat.aov <- batch_anova(data = combat.data,
  #                                       to.adjust = y.transformed.cols,
  #                                       batch = "batch")
  # 
  # zero.infl.before.combat.aov <- batch_anova(data = combat.data,
  #                                            to.adjust = y.0infl.cols,
  #                                            batch = "batch")
  # 
  # zero.infl.after.transform.before.combat.aov <- batch_anova(data = combat.data,
  #                                                         to.adjust = y.0infl.transformed.cols,
  #                                                         batch = "batch") 
  #-----------------------------------------------------------------
  #=================================================================
  
  # designate transposed matrix for adjustment
  my.edata.y <- combat.data[, t(as.matrix(.SD)), .SDcols = y.cols]
  my.edata.y.0infl <- combat.data[, t(as.matrix(.SD)), .SDcols = y.0infl.cols]
  
  # for transformed data
  my.edata.y.transformed <- combat.data[, t(as.matrix(.SD)), .SDcols = y.transformed.cols]
  my.edata.y.0infl.transformed <- combat.data[, t(as.matrix(.SD)), .SDcols = y.0infl.transformed.cols]
  
  # set batch as character string
  my.batch <- combat.data[, unname(unlist(batch))]
  
  # set phenotypes to adjust
  my.pheno <- combat.data[, .(batch)]
  
  # only intercept term, no covariates
  my.formula <- ~1
  
  # create model matrix
  my.modcombat <- model.matrix(my.formula, data = my.pheno)
  
  # this seems to be necessary suddenly
  # https://support.bioconductor.org/p/95306/
  BiocParallel::register(BiocParallel::SerialParam())
  
  # combat on full data
  combat.edata.y <- sva::ComBat(dat = my.edata.y,
                                batch = my.batch,
                                mod = my.modcombat,
                                par.prior = F,
                                prior.plots = T)
  
  # reset pars
  par(mfrow=c(1,1))

  # combat on full data
  combat.edata.y.transformed <- sva::ComBat(dat = my.edata.y.transformed,
                                            batch = my.batch,
                                            mod = my.modcombat,
                                            par.prior = F,
                                            prior.plots = T)
  
  # reset pars
  par(mfrow=c(1,1))
  
  # combat on zero-inflated data
  combat.edata.0infl <- sva::ComBat(dat = my.edata.y.0infl,
                                        batch = my.batch,
                                        mod = my.modcombat,
                                        par.prior = F,
                                        prior.plots = T)
  
  # reset pars
  par(mfrow=c(1,1))
  
  # combat on zero-inflated & transformed data data
  combat.edata.0infl.transformed <- sva::ComBat(dat = my.edata.y.0infl.transformed,
                                                 batch = my.batch,
                                                 mod = my.modcombat,
                                                 par.prior = F,
                                                 prior.plots = T)
  
  # reset pars
  par(mfrow=c(1,1))
  
  # re-enter adjusted data into dat
  combat.data[, (y.cols) := as.data.table(t(combat.edata.y))]
  combat.data[, (y.transformed.cols) := as.data.table(t(combat.edata.y.transformed))]
  combat.data[, (y.0infl.cols) := as.data.table(t(combat.edata.0infl))]
  combat.data[, (y.0infl.transformed.cols) := as.data.table(t(combat.edata.0infl.transformed))]
  
  # Now the data is back in combat.data
  ###
  # END: ComBat 
  ###
  
  #-----------------------------------------------------------------
  # Post-ComBat ANOVA
  #-----------------------------------------------------------------
  
  # full.after.combat.aov <- batch_anova(data = combat.data,
  #                                      to.adjust = y.cols,
  #                                      batch = "batch")
  # 
  # full.after.transform.after.combat.aov <- batch_anova(data = combat.data,
  #                                                      to.adjust = y.transformed.cols,
  #                                                      batch = "batch")
  # 
  # zero.infl.after.combat.aov <- batch_anova(data = combat.data,
  #                                           to.adjust = y.0infl.cols,
  #                                           batch = "batch")
  # 
  # # of the (prior to combat) transformed data post combat
  # zero.infl.after.transform.after.combat.aov <- batch_anova(data = combat.data,
  #                                                           to.adjust = y.0infl.transformed.cols,
  #                                                           batch = "batch")
  
  #-----------------------------------------------------------------
  # fit lm on each ComBat chunk (96)
  #-----------------------------------------------------------------
  
  # now compute everything for 96 data sets
  # loop -------------------------------------------------
  lm.cor.res <- lapply(my.combat.run$sub.run, function(f){
    
    # f <- 81 # debug
    # formulas
    my.formula.full <- as.formula(paste0("y.", f, " ~ ", "x.", f))
    my.formula.full.transformed <- as.formula(paste0("y.", f, ".transformed ~ ", "x.", f))
    my.formula.0infl <- as.formula(paste0("y.0infl.", f, " ~ ", "x.", f))
    my.formula.0infl.transformed <- as.formula(paste0("y.0infl.", f, ".transformed ", " ~ ", "x.", f))
    
    # calc the lm
    linmod.full.data <- summary(lm(my.formula.full, data = combat.data)) 
    linmod.full.data.transformed <- summary(lm(my.formula.full.transformed, data = combat.data)) 
    linmod.zero.inflated <- summary(lm(my.formula.0infl, data = combat.data)) 
    linmod.zero.inflated.transformed <- summary(lm(my.formula.0infl.transformed, data = combat.data)) 
    
    # do the rank correlation
    cor.full.data <- tidy(combat.data[, cor.test(x = get(paste0("x.", f)), y = get(paste0("y.", f)), method = "spearman")])
    cor.full.data.transformed <- tidy(combat.data[, cor.test(x = get(paste0("x.", f)), y = get(paste0("y.", f, ".transformed")), method = "spearman")])
    cor.zero.inflated <- tidy(combat.data[, cor.test(x = get(paste0("x.", f)), y = get(paste0("y.0infl.", f)), method = "spearman")])
    cor.zero.inflated.transformed <- tidy(combat.data[, cor.test(x = get(paste0("x.", f)), y = get(paste0("y.0infl.", f, ".transformed")), method = "spearman")])
    
    # compile results
    res <- data.table(spearman.cor.full.data = cor.full.data$estimate,
                      spearman.cor.pval.full.data = cor.full.data$p.value,
                      spearman.cor.full.data.transformed = cor.full.data.transformed$estimate,
                      spearman.cor.pval.full.data.transformed = cor.full.data.transformed$p.value,
                      linmod.r2.full.data = linmod.full.data$r.squared,
                      linmod.pval.full.data = linmod.full.data$coefficients[grep("x.", rownames(linmod.full.data$coefficients)), "Pr(>|t|)"],
                      linmod.beta.full.data = linmod.full.data$coefficients[grep("x.", rownames(linmod.full.data$coefficients)),"Estimate"],
                      linmod.r2.full.data.transformed = linmod.full.data.transformed$r.squared,
                      linmod.pval.full.data.transformed = linmod.full.data.transformed$coefficients[grep("x.", rownames(linmod.full.data.transformed$coefficients)), "Pr(>|t|)"],
                      linmod.beta.full.data.transformed = linmod.full.data.transformed$coefficients[grep("x.", rownames(linmod.full.data.transformed$coefficients)),"Estimate"],
                      spearman.cor.zero.inflated = cor.zero.inflated$estimate,
                      spearman.cor.pval.zero.inflated = cor.zero.inflated$p.value,
                      linmod.r2.zero.inflated = linmod.zero.inflated$r.squared,
                      linmod.pval.zero.inflated = linmod.zero.inflated$coefficients[grep("x.", rownames(linmod.zero.inflated$coefficients)),"Pr(>|t|)"],
                      linmod.beta.zero.inflated = linmod.zero.inflated$coefficients[grep("x.", rownames(linmod.zero.inflated$coefficients)),"Estimate"],
                      spearman.cor.zero.inflated.transformed = cor.zero.inflated.transformed$estimate,
                      spearman.cor.pval.zero.inflated.transformed = cor.zero.inflated.transformed$p.value,
                      linmod.r2.zero.inflated.transformed = linmod.zero.inflated.transformed$r.squared,
                      linmod.pval.zero.inflated.transformed = linmod.zero.inflated.transformed$coefficients[grep("x.", rownames(linmod.zero.inflated.transformed$coefficients)),"Pr(>|t|)"],
                      linmod.beta.zero.inflated.transformed = linmod.zero.inflated.transformed$coefficients[grep("x.", rownames(linmod.zero.inflated.transformed$coefficients)),"Estimate"])
    
    # return res dt just created
    return(res)
  }) 
  # End: loop --------------------------------------------
  
  # bind together 
  lm.cor.res <- rbindlist(lm.cor.res)
  
  # add infos + infos from anova
  lm.cor.res[ , `:=`(num = my.combat.run$num,
                     combat.run = my.combat.run$combat.run,
                     combat.sub.run = my.combat.run$sub.run,
                     realization = my.combat.run$realization,
                     effekt = my.combat.run$effekte,
                     n = my.combat.run$n,
                     proz0 = my.combat.run$proz0,
                     categart = my.combat.run$categart,
                     categnum = my.combat.run$categnum,
                     batch.effect = my.combat.run$batch
                     # p.ANOVA.full.pre.ComBat = full.before.combat.aov$p.values,
                     # p.ANOVA.full.post.ComBat = full.after.combat.aov$p.values,
                     # p.ANOVA.full.post.transform.pre.ComBat = full.after.transform.before.combat.aov$p.values,
                     # p.ANOVA.full.post.transform.post.ComBat = full.after.transform.after.combat.aov$p.values,
                     # p.ANOVA.zero.infl.pre.ComBat = zero.infl.before.combat.aov$p.values,
                     # p.ANOVA.zero.infl.post.ComBat = zero.infl.after.combat.aov$p.values,
                     # p.ANOVA.zero.infl.post.transformation.pre.ComBat = zero.infl.after.transform.before.combat.aov$p.values,
                     # p.ANOVA.zero.infl.post.transformation.post.ComBat = zero.infl.after.transform.after.combat.aov$p.values
                     )]
  
  #-----------------------------------------------------------------
  # Form Categories over zero-inflated data
  #-----------------------------------------------------------------
  my.categart <- as.character(unique(my.combat.run$categart))
  my.categnum <- (unique(my.combat.run$categnum))
  
  #get the cols to categorise
  cols.to.categorise <- grep("^y.0infl.[0-9]+$", names(combat.data), value = T)
  
  if(my.categart == "quantile") {
    
    # loop through each col and create ordered factor based on quantile
    categorised.cols <- combat.data[ , lapply(.SD, function(g){
      
      # i <- combat.data$y.0infl.45 # debug
      dummy <- data.table(data.no.categ = g)
      dummy[data.no.categ > 0, data.categ :=  cut(data.no.categ,
                                                  breaks = unique(quantile(data.no.categ,
                                                                           probs = seq(0, 1, 1 / my.categnum))),
                                                  include.lowest = T)]
      categs.created <- dummy[, levels(data.categ)]
      dummy[data.no.categ <= 0, data.categ := factor(0, labels =  "[0]", ordered = T)]
      dummy[, data.categ := factor(data.categ, levels = c("[0]", categs.created), ordered = T)]
      
      # get output and return it
      output <- dummy$data.categ
      return(output)
    }), .SDcols = cols.to.categorise]
    
  } else if(my.categart == "bereiche"){
    
    # loop through each col and create ordered factor based on range
    categorised.cols <- combat.data[ , lapply(.SD, function(h){
      
      # i <- combat.data$y.0infl.45 # debug
      dummy <- data.table(data.no.categ = h)
      dummy[data.no.categ > 0, data.categ :=  cut(data.no.categ,
                                                  breaks = seq(0, max(data.no.categ),
                                                               length.out = my.categnum + 1),
                                                  include.lowest = T)]
      categs.created <- dummy[, levels(data.categ)]
      dummy[data.no.categ <= 0, data.categ := factor(0, labels =  "[0]", ordered = T)]
      dummy[, data.categ := factor(data.categ, levels = c("[0]", categs.created), ordered = T)]
      
      # get output and return it
      output <- dummy$data.categ
      return(output)
    }), .SDcols = cols.to.categorise]
    
  } else {
    stop("Error")
  }
  
  # rename
  names(categorised.cols) <- paste0(names(categorised.cols), ".categorical")
  
  # enter into combat.data for processing
  combat.data[ , names(categorised.cols) := categorised.cols]
  
  #-----------------------------------------------------------------
  # Fit Models on categorical data
  #-----------------------------------------------------------------
  lm.categ.res.raw <- lapply(my.combat.run$sub.run, function(j){
    
    # formulas for model definition
    dicho.val.name <- paste0("y.0infl.", j)
    categ.val.name <- paste0("y.0infl.", j, ".categorical")
    my.formula.linmod.dicho <- as.formula(paste0(dicho.val.name, "> 0 ~ ", "x.", j))
    my.formula.linmod.logit <- as.formula(paste0(categ.val.name," ~ ", "x.", j))
    
    # run the model
    linmod.dicho <- summary(glm(formula = my.formula.linmod.dicho, family = "binomial", data = combat.data))
    logit.mod <- ordinal::clm(formula = my.formula.linmod.logit, data = combat.data)
    
    # extract coefficients
    #glm
    linmod.dicho.coefs <- setDT(as.data.frame(coefficients(linmod.dicho)), keep.rownames = T)
    linmod.dicho.pval <- unlist(linmod.dicho.coefs[rn == grep("x.[0-9]+$", linmod.dicho.coefs$rn, value = T), "Pr(>|z|)"])
    linmod.dicho.beta <- unlist(linmod.dicho.coefs[rn == grep("x.[0-9]+$", linmod.dicho.coefs$rn, value = T), "Estimate"])
    
    # ordinal
    logit.coeffs <- as.data.table(as.data.frame(summary(logit.mod)$coefficients), keep.rownames = T)
    logit.beta <- logit.mod$beta
    logit.pval <- unlist(logit.coeffs[rn == grep("x.[0-9]+$", logit.coeffs$rn, value = T), "Pr(>|z|)"])
    logit.aic <- as.numeric(levels(logit.mod$info$AIC))
    
    # enter coefficients into result file
    res <- data.table(dicho.pval = linmod.dicho.pval,
                      dicho.beta = linmod.dicho.beta,
                      dicho.AIC = linmod.dicho$aic,
                      logit.beta = logit.beta,
                      logit.pval = logit.pval,
                      logit.AIC = logit.aic)
    
    # return res
    return(res)
  })
  
  lm.categ.res <- rbindlist(lm.categ.res.raw)
  
  lm.cor.res[ , names(lm.categ.res) := lm.categ.res]
  
  # return
  return(lm.cor.res)
  
}, mc.cores = number.of.cores, mc.cleanup = T) # END OUTER LOOP
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#=============================================================#

# return warnings
warnings()
```

```{r save}
# bind everything together
all.scenarios <- rbindlist(all.combat.runs.raw)

# Save for use in STEP2
save_csv_carl(file = all.scenarios,
              file_name = "SimulationResultsPreComBatINTForSTEP2",
              subfolder = "results")
```

```{r SessionInfo, echo=F, results='markup'}
sessionInfo()
```            
